/*
 * Provides an API for the  Libpod library
 *
 * This documentation describes the Podman v2.0 RESTful API. It replaces the Podman v1.0 API and was initially delivered along with Podman v2.0.  It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  See podman-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v3.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v3.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v3.0.0/libpod/images/json' | jq
 *
 * API version: 3.2.0
 * Contact: podman@lists.podman.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse20016 struct {
	ApiVersion string `json:"ApiVersion,omitempty"`
	Arch string `json:"Arch,omitempty"`
	BuildTime string `json:"BuildTime,omitempty"`
	Components []ComponentVersion `json:"Components,omitempty"`
	Experimental bool `json:"Experimental,omitempty"`
	GitCommit string `json:"GitCommit,omitempty"`
	GoVersion string `json:"GoVersion,omitempty"`
	KernelVersion string `json:"KernelVersion,omitempty"`
	MinAPIVersion string `json:"MinAPIVersion,omitempty"`
	Os string `json:"Os,omitempty"`
	Platform *interface{} `json:"Platform,omitempty"`
	Version string `json:"Version,omitempty"`
}
